### ISSUE TITLE
启动后报AssertionError

### ISSUE THREAD

**Issue by xi-yue-233** [hgjazhgj/GenshinAutoFish#6]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\GenshinAutoFish-1.3.1\GenshinAutoFish-1.3.1\main.py", line 51, in <module>
    window = Window('原神')
  File "C:\Users\Administrator\Downloads\GenshinAutoFish-1.3.1\GenshinAutoFish-1.3.1\main.py", line 21, in __init__
    assert self.hWnd
AssertionError
问问为什么会报这个错

**Comment by xi-yue-233** [comment]
没事了，要先开原神才能运行这个程序
